#version: '3.9'  # Sử dụng phiên bản 3.9 hoặc cao hơn của cú pháp Docker Compose
#
#services:
#  petclinic:
#    build:
#      context: .
#    ports:
#      - "8000:8000"
#      - "8080:8080"
#    environment:
#      - SERVER_PORT=8080
#      - MYSQL_URL=jdbc:mysql://mysqlserver/api
#    volumes:
#      - ./:/app
#    depends_on:
#      - mysqlserver
#
#  mysqlserver:
#    image: mysql:8.0
#    ports:
#      - "3307:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=16102003
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=16102003
#      - MYSQL_DATABASE=api
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - mysql_config:/etc/mysql/conf.d
#
#volumes:
#  mysql_data:
#  mysql_config:
